### ISSUE TITLE
Pick A documentation Section

### ISSUE THREAD

**Issue by vsantosu** [TruenoDB/documentation#2]
Please choose one document section and write down here as a comment.

I will choose:

Trueno
Motivation
Quick Start
Deployment/Uninstall
- Installation
- Configuration
- CLI Flags
- Centralized Deployment
- Distributed Deployment
- Uninstall

**Comment by ebarsallo** [comment]
API & Drivers
- Graph, Vertex, Edge
- Gremlin Queries

**Comment by maverick-zhn** [comment]
API & Drivers
- Compute API

Compute

Note: I can help with some other sections in which you need help.

**Comment by ebarsallo** [comment]
Documentation is updated with changes in Trueno as April 2017.
